project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-T87WCP4N96"
  title: "Arjun Krishna"
  page-footer:
    #    center:
      #      - icon: linkedin
      #        href: https://www.linkedin.com/in/arjun-kris/
      #      - icon: twitter
      #        href: https://twitter.com/akrishna42
      #      - icon: github
        #        href: https://github.com/arjun-krishna/
    left:
      - text: Arjun Krishna © 2025.
  favicon: assets/favicon.ico
  open-graph:
    image-width: 128
    image-height: 128
  twitter-card:
    creator: "@akrishna42"
  site-url: "https://arjun-krishna.github.io/"
  description: "Personal webpage containing blogs and notes on topics in Robotics and Machine Learning."
  navbar:
    title: false
    background: dark
    left:
      - text: About
        href: index.qmd
      # - text: Blog
      #  href: blog/index.qmd
      - text: CV
        href: https://drive.google.com/file/d/1wP5hoQ1Tk6S2Lz4q730viUcCQdL9BIBo/view?usp=sharing
    right:
      - icon: envelope-fill
        href: arjk [at] upenn.edu
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=XsYoY2QAAAAJ&hl=en
#      - icon: 0-circle-fill
#        href: https://orcid.org/0000-0001-8558-281X
      - icon: twitter
        href: https://twitter.com/akrishna42
      - icon: github
        href: https://github.com/arjun-krishna/

format:
  html:
    theme: lux
    css: styles.css
    toc: true
